import { StyleSheet } from 'react-native';
import { WEB_PLAYER_ACCENT, WEB_PLAYER_SIDEBAR_WIDTH } from './utils';

export { WEB_PLAYER_ACCENT, WEB_PLAYER_SIDEBAR_WIDTH };

export const webPlayerStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#020817',
  },
  videoStage: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#000',
  },
  videoShadeTop: {
    ...StyleSheet.absoluteFillObject,
    bottom: '78%' as any,
    backgroundColor: 'rgba(2, 6, 23, 0.18)',
  },
  videoShadeBottom: {
    ...StyleSheet.absoluteFillObject,
    top: '68%' as any,
    backgroundColor: 'rgba(2, 6, 23, 0.22)',
  },
  topOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    paddingTop: 22,
    paddingBottom: 12,
  },
  brandCluster: {
    gap: 4,
    maxWidth: '55%',
  },
  brandText: {
    color: '#f8fafc',
    fontSize: 30,
    fontWeight: '800',
  },
  playlistText: {
    color: '#93c5fd',
    fontSize: 14,
    fontWeight: '600',
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  clockText: {
    color: '#e2e8f0',
    fontSize: 22,
    fontWeight: '700',
  },
  chromeBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chromeBtnTxt: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '700',
  },
  sidebar: {
    position: 'absolute',
    top: 88,
    left: 24,
    bottom: 160,
    width: WEB_PLAYER_SIDEBAR_WIDTH,
    zIndex: 8,
    backgroundColor: 'rgba(5, 10, 20, 0.76)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.14)',
    overflow: 'hidden' as any,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.42,
    shadowRadius: 34,
  },
  sidebarGuide: {
    position: 'absolute',
    top: 88,
    left: WEB_PLAYER_SIDEBAR_WIDTH + 36,
    bottom: 160,
    width: 420,
    zIndex: 9,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.18)',
    backgroundColor: 'rgba(8, 15, 28, 0.72)',
    overflow: 'hidden' as any,
  },
  sidebarGuideHeader: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(96, 165, 250, 0.14)',
  },
  sidebarGuideEyebrow: {
    color: '#60a5fa',
    fontSize: 11,
    fontWeight: '800',
  },
  sidebarGuideTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '800',
    marginTop: 4,
  },
  sidebarGuideList: {
    padding: 12,
  },
  sidebarGuideItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    padding: 12,
    marginBottom: 8,
  },
  sidebarGuideItemNow: {
    borderColor: 'rgba(56, 189, 248, 0.55)',
    backgroundColor: 'rgba(20, 52, 84, 0.55)',
  },
  sidebarGuideItemCatchup: {
    borderColor: 'rgba(125, 211, 252, 0.24)',
  },
  sidebarGuideTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  sidebarGuideTime: {
    color: '#93c5fd',
    fontSize: 11,
    fontWeight: '700',
  },
  sidebarGuideNow: {
    color: '#03111f',
    fontSize: 9,
    fontWeight: '800',
    backgroundColor: WEB_PLAYER_ACCENT,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  sidebarGuideCatchup: {
    color: '#bae6fd',
    fontSize: 9,
    fontWeight: '800',
  },
  sidebarGuideProgramTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 8,
    lineHeight: 19,
  },
  sidebarGuideDesc: {
    color: '#93c5fd',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
  },
  sidebarGuideTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(191, 219, 254, 0.18)',
    overflow: 'hidden',
    marginTop: 10,
  },
  sidebarGuideFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  sidebarGuideEmpty: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    padding: 14,
  },
  sidebarGuideEmptyTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
  },
  sidebarGuideEmptyText: {
    color: '#93c5fd',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  mainGuide: {
    position: 'absolute',
    top: 84,
    left: 32,
    right: 32,
    bottom: 154,
    zIndex: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.32)',
    backgroundColor: 'rgba(8, 15, 28, 0.94)',
    overflow: 'hidden' as any,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.32,
    shadowRadius: 30,
  },
  mainGuideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minHeight: 154,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(96, 165, 250, 0.14)',
  },
  mainGuideTitleBlock: {
    flex: 1,
  },
  mainGuideEyebrow: {
    color: '#60a5fa',
    fontSize: 11,
    fontWeight: '800',
  },
  mainGuideTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 4,
  },
  mainGuidePip: {
    width: 280,
    height: 158,
    borderRadius: 12,
    overflow: 'hidden' as any,
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.24)',
  },
  mainGuideCloseBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  mainGuideCloseTxt: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
  },
  mainGuideGroupBar: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(96, 165, 250, 0.14)',
    backgroundColor: 'rgba(5, 10, 19, 0.36)',
  },
  mainGuideGroupLabel: {
    color: '#93c5fd',
    fontSize: 11,
    fontWeight: '800',
  },
  mainGuideGroupList: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
  },
  mainGuideGroupChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  mainGuideGroupChipActive: {
    borderColor: WEB_PLAYER_ACCENT,
    backgroundColor: WEB_PLAYER_ACCENT,
  },
  mainGuideGroupChipText: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '800',
  },
  mainGuideGroupChipTextActive: {
    color: '#03111f',
  },
  mainGuideList: {
    padding: 12,
  },
  mainGuideChannelRow: {
    flexDirection: 'row',
    minHeight: 106,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    marginBottom: 8,
    overflow: 'hidden' as any,
  },
  mainGuideChannelRowActive: {
    borderColor: 'rgba(56, 189, 248, 0.65)',
    backgroundColor: 'rgba(20, 52, 84, 0.9)',
  },
  mainGuideChannelCell: {
    width: 260,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    borderRightWidth: 1,
    borderRightColor: 'rgba(96, 165, 250, 0.12)',
  },
  mainGuideChannelNumber: {
    width: 34,
    color: '#93c5fd',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'right',
  },
  mainGuideChannelName: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '800',
  },
  mainGuideChannelGroup: {
    color: '#93c5fd',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 4,
  },
  mainGuideProgramRail: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  mainGuideProgramCard: {
    width: 220,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.86)',
    padding: 12,
    marginRight: 10,
  },
  mainGuideProgramCardNow: {
    borderColor: 'rgba(56, 189, 248, 0.6)',
    backgroundColor: 'rgba(20, 52, 84, 0.92)',
  },
  mainGuideProgramCardCatchup: {
    borderColor: 'rgba(125, 211, 252, 0.28)',
  },
  mainGuideTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mainGuideTime: {
    color: '#93c5fd',
    fontSize: 12,
    fontWeight: '800',
  },
  mainGuideNow: {
    color: '#03111f',
    fontSize: 9,
    fontWeight: '800',
    backgroundColor: WEB_PLAYER_ACCENT,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  mainGuideCatchup: {
    color: '#bae6fd',
    fontSize: 9,
    fontWeight: '800',
  },
  mainGuideProgramTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 8,
    lineHeight: 19,
  },
  mainGuideDesc: {
    color: '#93c5fd',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 7,
  },
  mainGuideTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(191, 219, 254, 0.18)',
    overflow: 'hidden',
    marginTop: 10,
  },
  mainGuideFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  mainGuideEmpty: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.86)',
    padding: 16,
  },
  mainGuideNoDataCard: {
    width: 220,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    padding: 12,
    justifyContent: 'center',
  },
  mainGuideEmptyTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '800',
  },
  mainGuideEmptyText: {
    color: '#93c5fd',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 7,
  },
  sidebarHeader: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
  },
  sidebarHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(226, 232, 240, 0.08)',
  },
  sidebarHeading: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '800',
  },
  sidebarSub: {
    color: '#60a5fa',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  groupsToggleBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.16)',
    backgroundColor: 'rgba(15, 23, 42, 0.58)',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  groupsToggleBtnActive: {
    backgroundColor: WEB_PLAYER_ACCENT,
    borderColor: WEB_PLAYER_ACCENT,
  },
  groupsToggleTxt: {
    color: '#93c5fd',
    fontSize: 12,
    fontWeight: '800',
  },
  groupsToggleTxtActive: {
    color: '#03111f',
  },
  sidebarBody: {
    flex: 1,
    flexDirection: 'row',
    minHeight: 0 as any,
  },
  groupRail: {
    width: 130,
    borderRightWidth: 1,
    borderRightColor: 'rgba(96, 165, 250, 0.14)',
    backgroundColor: 'rgba(5, 10, 19, 0.42)',
  },
  groupRailScroll: {
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  groupRailItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  groupRailItemActive: {
    backgroundColor: 'rgba(31, 162, 255, 0.18)',
    borderColor: 'rgba(56, 189, 248, 0.65)',
  },
  groupRailTxt: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  groupRailTxtActive: {
    color: '#ffffff',
  },
  channelList: {
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 14,
  },
  channelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 76,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    overflow: 'hidden' as any,
  },
  channelRowCurrent: {
    backgroundColor: 'rgba(15, 23, 42, 0.64)',
    borderColor: 'rgba(226, 232, 240, 0.1)',
  },
  channelRowHighlighted: {
    backgroundColor: 'rgba(226, 232, 240, 0.95)',
    borderColor: 'rgba(255, 255, 255, 0.95)',
    shadowColor: '#38bdf8',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
  },
  channelSelectionRail: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 999,
    backgroundColor: 'transparent',
    marginLeft: -2,
  },
  channelSelectionRailActive: {
    backgroundColor: WEB_PLAYER_ACCENT,
  },
  channelNumber: {
    width: 34,
    color: '#8fb9e8',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'right',
  },
  channelNumberHighlighted: {
    color: '#0f172a',
  },
  channelMeta: {
    flex: 1,
    minWidth: 0,
  },
  channelTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  channelName: {
    flex: 1,
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '800',
  },
  channelNameCurrent: {
    color: '#dbeafe',
  },
  channelNameHighlighted: {
    color: '#061225',
  },
  channelProgram: {
    color: '#93c5fd',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  channelProgramHighlighted: {
    color: '#334155',
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(239, 68, 68, 0.96)',
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  liveBadgeDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  liveBadgeTxt: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '800',
  },
  logoFallback: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#102033',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.18)',
  },
  logoFallbackTxt: {
    color: '#bfdbfe',
    fontSize: 14,
    fontWeight: '800',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(2, 6, 23, 0.45)',
    gap: 12,
  },
  loadingText: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '600',
  },
  infoOverlay: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 22,
    zIndex: 7,
    gap: 12,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 18,
    backgroundColor: 'rgba(9, 15, 27, 0.74)',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.2)',
  },
  infoChannelName: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '800',
  },
  infoProgramName: {
    color: '#dbeafe',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 3,
  },
  infoTime: {
    color: '#7dd3fc',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  infoActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  infoActionBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
  },
  infoActionBtnActive: {
    backgroundColor: WEB_PLAYER_ACCENT,
    borderColor: WEB_PLAYER_ACCENT,
  },
  infoActionTxt: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '700',
  },
  infoActionTxtActive: {
    color: '#03111f',
  },
  programProgressWrap: {
    paddingHorizontal: 8,
  },
  programProgressTrack: {
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    overflow: 'hidden',
  },
  programProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: WEB_PLAYER_ACCENT,
  },
  guideRail: {
    borderRadius: 18,
    backgroundColor: 'rgba(7, 12, 22, 0.76)',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.18)',
    paddingTop: 14,
    paddingBottom: 12,
  },
  guideRailHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  guideRailTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  guideRailHint: {
    color: '#7dd3fc',
    fontSize: 12,
    fontWeight: '600',
  },
  guideRailScroll: {
    paddingHorizontal: 18,
    gap: 10,
  },
  guideCard: {
    width: 240,
    borderRadius: 14,
    padding: 14,
    marginRight: 10,
    backgroundColor: '#101b2d',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
  },
  guideCardActive: {
    backgroundColor: '#143454',
    borderColor: 'rgba(56, 189, 248, 0.55)',
  },
  guideTime: {
    color: '#7dd3fc',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
  },
  guideTimeActive: {
    color: '#dbeafe',
  },
  guideTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
    minHeight: 38,
  },
  guideTitleActive: {
    color: '#fff',
  },
  guideDesc: {
    color: '#93c5fd',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 8,
  },
  guideTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(191, 219, 254, 0.18)',
    overflow: 'hidden',
    marginTop: 12,
  },
  guideFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  noGuideCard: {
    width: 300,
    borderRadius: 14,
    padding: 16,
    backgroundColor: '#101b2d',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.1)',
  },
  noGuideTitle: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  noGuideText: {
    color: '#93c5fd',
    fontSize: 12,
    marginTop: 8,
    lineHeight: 18,
  },
  epgBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    gap: 8,
    marginTop: 12,
    marginRight: 18,
  },
  epgBadgeTxt: {
    color: '#93c5fd',
    fontSize: 11,
    fontWeight: '600',
  },
  videoPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#020617',
    gap: 10,
  },
  videoPlaceholderIcon: {
    color: '#93c5fd',
    fontSize: 42,
    fontWeight: '700',
  },
  videoPlaceholderTxt: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '700',
  },
  videoPlaceholderSub: {
    color: '#93c5fd',
    fontSize: 12,
    maxWidth: 760,
  },
  empty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#020817',
  },
  emptyTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
  },
  emptyDesc: {
    color: '#93c5fd',
    fontSize: 14,
  },
  emptyBtn: {
    marginTop: 10,
    borderRadius: 12,
    backgroundColor: WEB_PLAYER_ACCENT,
    paddingHorizontal: 24,
    paddingVertical: 14,
  },
  emptyBtnTxt: {
    color: '#03111f',
    fontSize: 14,
    fontWeight: '800',
  },
});
