import { StyleSheet } from 'react-native';
import { Theme, withAlpha } from '../../theme/themes';
import { PANEL_ALPHA, PANEL_W, TINT_ALPHA, TOTAL_W, TV } from './ChannelListPanel.constants';

export const createChannelListPanelStyles = (theme: Theme) => StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    zIndex: 15,
    elevation: 15,
  },
  panel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: TOTAL_W,
    backgroundColor: withAlpha(theme.bg, PANEL_ALPHA),
    borderRightWidth: 1,
    borderRightColor: theme.border,
    zIndex: 20,
    elevation: 20,
  },
  header: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  headerLeft: {
    width: PANEL_W,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: TV ? 10 : 8,
    paddingTop: TV ? 16 : 12,
    paddingBottom: TV ? 8 : 6,
  },
  headerEpg: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: TV ? 12 : 10,
    paddingBottom: TV ? 10 : 8,
    borderLeftWidth: 1,
    borderLeftColor: theme.border,
    backgroundColor: withAlpha(theme.surface, TINT_ALPHA),
  },
  headerEpgTxt: {
    color: theme.textMuted,
    fontSize: TV ? 10 : 9,
    fontWeight: '800',
    letterSpacing: 2,
  },
  groupsArrow: {
    width: TV ? 34 : 28,
    height: TV ? 34 : 28,
    borderRadius: 8,
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  groupsArrowTxt: {
    color: theme.textSub,
    fontSize: TV ? 22 : 18,
    fontWeight: '700',
    lineHeight: TV ? 26 : 22,
  },
  headerTitle: {
    color: theme.text,
    fontSize: TV ? 16 : 14,
    fontWeight: '800',
    flex: 1,
    letterSpacing: -0.3,
  },
  headerCount: {
    color: theme.textMuted,
    fontSize: TV ? 12 : 10,
    fontWeight: '700',
  },
  searchArea: {
    width: PANEL_W,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.card,
    borderRadius: 8,
    marginHorizontal: TV ? 10 : 8,
    marginTop: TV ? 8 : 6,
    marginBottom: TV ? 4 : 3,
    paddingHorizontal: 10,
    gap: 6,
    height: TV ? 36 : 30,
    borderWidth: 1,
    borderColor: theme.border,
  },
  searchIcon: { fontSize: 12 },
  searchInput: {
    flex: 1,
    color: theme.textSub,
    fontSize: TV ? 13 : 11,
    fontWeight: '500',
    paddingVertical: 0,
  },
  clearBtn: { color: theme.textMuted, fontSize: 11, fontWeight: '700', padding: 4 },
  tabsArea: {
    width: PANEL_W,
  },
  tabsRow: {
    flexDirection: 'row',
    marginHorizontal: TV ? 10 : 8,
    marginBottom: TV ? 6 : 4,
    gap: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: TV ? 6 : 4,
    borderRadius: 6,
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: theme.cardActive,
    borderColor: theme.accent,
  },
  tabTxt: { color: theme.textMuted, fontSize: TV ? 11 : 9, fontWeight: '700' },
  tabTxtActive: { color: theme.accent },
  groupsBtn: {
    paddingVertical: TV ? 6 : 4,
    paddingHorizontal: TV ? 12 : 8,
    borderRadius: 6,
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupsBtnTxt: { color: theme.textMuted, fontSize: TV ? 11 : 9, fontWeight: '700' },
  columnHeadings: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: theme.border,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    backgroundColor: theme.surface,
  },
  channelHeading: {
    width: PANEL_W,
    paddingHorizontal: TV ? 12 : 10,
    paddingVertical: TV ? 8 : 6,
  },
  guideHeading: {
    flex: 1,
    paddingHorizontal: TV ? 12 : 10,
    paddingVertical: TV ? 8 : 6,
    borderLeftWidth: 1,
    borderLeftColor: theme.border,
  },
  columnEyebrow: {
    color: theme.textMuted,
    fontSize: TV ? 9 : 8,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  columnTitle: {
    color: theme.textSub,
    fontSize: TV ? 13 : 11,
    fontWeight: '800',
    marginTop: 2,
  },
  content: {
    flex: 1,
    flexDirection: 'row',
  },
  channelCol: {
    width: PANEL_W,
    flex: 0,
  },
  epgCol: {
    flex: 1,
    borderLeftWidth: 1,
    borderLeftColor: theme.border,
    backgroundColor: withAlpha(theme.surface, TINT_ALPHA),
    overflow: 'hidden',
  },
  emptyWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  emptyTxt: {
    color: theme.textMuted,
    fontSize: TV ? 13 : 11,
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: 22,
  },
});
